export const supportedLanguages = [
	"1c",
	"abnf",
	"accesslog",
	"actionscript",
	"ada",
	"angelscript",
	"apache",
	"applescript",
	"arcade",
	"arduino",
	"armasm",
	"xml",
	"asciidoc",
	"aspectj",
	"autohotkey",
	"autoit",
	"avrasm",
	"awk",
	"axapta",
	"bash",
	"basic",
	"bnf",
	"brainfuck",
	"c",
	"cal",
	"capnproto",
	"ceylon",
	"clean",
	"clojure",
	"clojure-repl",
	"cmake",
	"coffeescript",
	"coq",
	"cos",
	"cpp",
	"crmsh",
	"crystal",
	"csharp",
	"csp",
	"css",
	"d",
	"markdown",
	"dart",
	"delphi",
	"diff",
	"django",
	"dns",
	"dockerfile",
	"dos",
	"dsconfig",
	"dts",
	"dust",
	"ebnf",
	"elixir",
	"elm",
	"ruby",
	"erb",
	"erlang-repl",
	"erlang",
	"excel",
	"fix",
	"flix",
	"fortran",
	"fsharp",
	"gams",
	"gauss",
	"gcode",
	"gherkin",
	"glsl",
	"gml",
	"go",
	"golo",
	"gradle",
	"graphql",
	"groovy",
	"haml",
	"handlebars",
	"haskell",
	"haxe",
	"hsp",
	"http",
	"hy",
	"inform7",
	"ini",
	"irpf90",
	"isbl",
	"java",
	"javascript",
	"jboss-cli",
	"json",
	"julia",
	"julia-repl",
	"kotlin",
	"lasso",
	"latex",
	"ldif",
	"leaf",
	"less",
	"lisp",
	"livecodeserver",
	"livescript",
	"llvm",
	"lsl",
	"lua",
	"makefile",
	"mathematica",
	"matlab",
	"maxima",
	"mel",
	"mercury",
	"mipsasm",
	"mizar",
	"perl",
	"mojolicious",
	"monkey",
	"moonscript",
	"n1ql",
	"nestedtext",
	"nginx",
	"nim",
	"nix",
	"node-repl",
	"nsis",
	"objectivec",
	"ocaml",
	"openscad",
	"oxygene",
	"parser3",
	"pf",
	"pgsql",
	"php",
	"php-template",
	"plaintext",
	"pony",
	"powershell",
	"processing",
	"profile",
	"prolog",
	"properties",
	"protobuf",
	"puppet",
	"purebasic",
	"python",
	"python-repl",
	"q",
	"qml",
	"r",
	"reasonml",
	"rib",
	"roboconf",
	"routeros",
	"rsl",
	"ruleslanguage",
	"rust",
	"sas",
	"scala",
	"scheme",
	"scilab",
	"scss",
	"shell",
	"smali",
	"smalltalk",
	"sml",
	"sqf",
	"sql",
	"stan",
	"stata",
	"step21",
	"stylus",
	"subunit",
	"swift",
	"taggerscript",
	"yaml",
	"tap",
	"tcl",
	"thrift",
	"tp",
	"twig",
	"typescript",
	"vala",
	"vbnet",
	"vbscript",
	"vbscript-html",
	"verilog",
	"vhdl",
	"vim",
	"wasm",
	"wren",
	"x86asm",
	"xl",
	"xquery",
	"zephir",
]

export const supportedLanguagesJson = [
	{ name: "1c", extension: ".bsl", color: "#e8512a" },
	{ name: "abnf", extension: ".abnf", color: "#6d8086" },
	{ name: "accesslog", extension: ".log", color: "#6d8086" },
	{ name: "actionscript", extension: ".as", color: "#e8a135" },
	{ name: "ada", extension: ".adb", color: "#02f88c" },
	{ name: "angelscript", extension: ".as", color: "#c7d7dc" },
	{ name: "apache", extension: ".conf", color: "#d22128" },
	{ name: "applescript", extension: ".applescript", color: "#101f1f" },
	{ name: "arcade", extension: ".arcade", color: "#199be2" },
	{ name: "arduino", extension: ".ino", color: "#00979d" },
	{ name: "armasm", extension: ".s", color: "#6d8086" },
	{ name: "xml", extension: ".xml", color: "#f60" },
	{ name: "asciidoc", extension: ".adoc", color: "#73a0c5" },
	{ name: "aspectj", extension: ".aj", color: "#a957b0" },
	{ name: "autohotkey", extension: ".ahk", color: "#6594b9" },
	{ name: "autoit", extension: ".au3", color: "#1c3552" },
	{ name: "avrasm", extension: ".asm", color: "#6d8086" },
	{ name: "awk", extension: ".awk", color: "#c30e9b" },
	{ name: "axapta", extension: ".xpp", color: "#00b4f0" },
	{ name: "bash", extension: ".sh", color: "#89e051" },
	{ name: "basic", extension: ".bas", color: "#ff0000" },
	{ name: "bnf", extension: ".bnf", color: "#6d8086" },
	{ name: "brainfuck", extension: ".bf", color: "#2f2530" },
	{ name: "c", extension: ".c", color: "#555555" },
	{ name: "cal", extension: ".cal", color: "#00b4f0" },
	{ name: "capnproto", extension: ".capnp", color: "#c42727" },
	{ name: "ceylon", extension: ".ceylon", color: "#dfa535" },
	{ name: "clean", extension: ".icl", color: "#3a81ad" },
	{ name: "clojure", extension: ".clj", color: "#db5855" },
	{ name: "clojure-repl", extension: ".clj", color: "#db5855" },
	{ name: "cmake", extension: ".cmake", color: "#da3434" },
	{ name: "coffeescript", extension: ".coffee", color: "#244776" },
	{ name: "coq", extension: ".v", color: "#d0b68c" },
	{ name: "cos", extension: ".cls", color: "#6d8086" },
	{ name: "cpp", extension: ".cpp", color: "#f34b7d" },
	{ name: "crmsh", extension: ".crm", color: "#6d8086" },
	{ name: "crystal", extension: ".cr", color: "#000100" },
	{ name: "csharp", extension: ".cs", color: "#178600" },
	{ name: "csp", extension: ".csp", color: "#6d8086" },
	{ name: "css", extension: ".css", color: "#563d7c" },
	{ name: "d", extension: ".d", color: "#ba595e" },
	{ name: "markdown", extension: ".md", color: "#083fa1" },
	{ name: "dart", extension: ".dart", color: "#00b4ab" },
	{ name: "delphi", extension: ".pas", color: "#b0ce4e" },
	{ name: "diff", extension: ".diff", color: "#88dddd" },
	{ name: "django", extension: ".html", color: "#0c4b33" },
	{ name: "dns", extension: ".zone", color: "#6d8086" },
	{ name: "dockerfile", extension: ".dockerfile", color: "#384d54" },
	{ name: "dos", extension: ".bat", color: "#c1f12e" },
	{ name: "dsconfig", extension: ".dsconfig", color: "#6d8086" },
	{ name: "dts", extension: ".dts", color: "#6d8086" },
	{ name: "dust", extension: ".dust", color: "#f7a600" },
	{ name: "ebnf", extension: ".ebnf", color: "#6d8086" },
	{ name: "elixir", extension: ".ex", color: "#6e4a7e" },
	{ name: "elm", extension: ".elm", color: "#60b5cc" },
	{ name: "ruby", extension: ".rb", color: "#701516" },
	{ name: "erb", extension: ".erb", color: "#701516" },
	{ name: "erlang-repl", extension: ".erl", color: "#b83998" },
	{ name: "erlang", extension: ".erl", color: "#b83998" },
	{ name: "excel", extension: ".xlsx", color: "#217346" },
	{ name: "fix", extension: ".fix", color: "#6d8086" },
	{ name: "flix", extension: ".flix", color: "#8db7c2" },
	{ name: "fortran", extension: ".f90", color: "#4d41b1" },
	{ name: "fsharp", extension: ".fs", color: "#b845fc" },
	{ name: "gams", extension: ".gms", color: "#6d8086" },
	{ name: "gauss", extension: ".gss", color: "#ffdd00" },
	{ name: "gcode", extension: ".gcode", color: "#d08cf2" },
	{ name: "gherkin", extension: ".feature", color: "#5b2063" },
	{ name: "glsl", extension: ".glsl", color: "#5686a5" },
	{ name: "gml", extension: ".gml", color: "#71c596" },
	{ name: "go", extension: ".go", color: "#00add8" },
	{ name: "golo", extension: ".golo", color: "#88562a" },
	{ name: "gradle", extension: ".gradle", color: "#02303a" },
	{ name: "graphql", extension: ".graphql", color: "#e10098" },
	{ name: "groovy", extension: ".groovy", color: "#4298b8" },
	{ name: "haml", extension: ".haml", color: "#ece2a9" },
	{ name: "handlebars", extension: ".hbs", color: "#f7931e" },
	{ name: "haskell", extension: ".hs", color: "#5e5086" },
	{ name: "haxe", extension: ".hx", color: "#df7900" },
	{ name: "hsp", extension: ".hsp", color: "#6d8086" },
	{ name: "http", extension: ".http", color: "#005c99" },
	{ name: "hy", extension: ".hy", color: "#7790b2" },
	{ name: "inform7", extension: ".ni", color: "#6d8086" },
	{ name: "ini", extension: ".ini", color: "#d1dbe0" },
	{ name: "irpf90", extension: ".f90", color: "#4d41b1" },
	{ name: "isbl", extension: ".isbl", color: "#6d8086" },
	{ name: "java", extension: ".java", color: "#b07219" },
	{ name: "javascript", extension: ".js", color: "#f1e05a" },
	{ name: "jboss-cli", extension: ".cli", color: "#6d8086" },
	{ name: "json", extension: ".json", color: "#292929" },
	{ name: "julia", extension: ".jl", color: "#a270ba" },
	{ name: "julia-repl", extension: ".jl", color: "#a270ba" },
	{ name: "kotlin", extension: ".kt", color: "#a97bff" },
	{ name: "lasso", extension: ".lasso", color: "#999999" },
	{ name: "latex", extension: ".tex", color: "#3d6117" },
	{ name: "ldif", extension: ".ldif", color: "#6d8086" },
	{ name: "leaf", extension: ".leaf", color: "#6d8086" },
	{ name: "less", extension: ".less", color: "#1d365d" },
	{ name: "lisp", extension: ".lisp", color: "#3fb68b" },
	{ name: "livecodeserver", extension: ".livecodescript", color: "#6d8086" },
	{ name: "livescript", extension: ".ls", color: "#499886" },
	{ name: "llvm", extension: ".ll", color: "#185619" },
	{ name: "lsl", extension: ".lsl", color: "#3d9970" },
	{ name: "lua", extension: ".lua", color: "#000080" },
	{ name: "makefile", extension: ".makefile", color: "#427819" },
	{ name: "mathematica", extension: ".m", color: "#dd1100" },
	{ name: "matlab", extension: ".m", color: "#e16737" },
	{ name: "maxima", extension: ".mac", color: "#6d8086" },
	{ name: "mel", extension: ".mel", color: "#6d8086" },
	{ name: "mercury", extension: ".m", color: "#ff2b2b" },
	{ name: "mipsasm", extension: ".s", color: "#6d8086" },
	{ name: "mizar", extension: ".miz", color: "#6d8086" },
	{ name: "perl", extension: ".pl", color: "#0298c3" },
	{ name: "mojolicious", extension: ".ep", color: "#0298c3" },
	{ name: "monkey", extension: ".monkey", color: "#6d8086" },
	{ name: "moonscript", extension: ".moon", color: "#ff4585" },
	{ name: "n1ql", extension: ".n1ql", color: "#ed9900" },
	{ name: "nestedtext", extension: ".nt", color: "#6d8086" },
	{ name: "nginx", extension: ".conf", color: "#009900" },
	{ name: "nim", extension: ".nim", color: "#ffc200" },
	{ name: "nix", extension: ".nix", color: "#7e7eff" },
	{ name: "node-repl", extension: ".js", color: "#f1e05a" },
	{ name: "nsis", extension: ".nsi", color: "#6d8086" },
	{ name: "objectivec", extension: ".m", color: "#438eff" },
	{ name: "ocaml", extension: ".ml", color: "#ef7a08" },
	{ name: "openscad", extension: ".scad", color: "#e5cd45" },
	{ name: "oxygene", extension: ".pas", color: "#cdd0e3" },
	{ name: "parser3", extension: ".p", color: "#6d8086" },
	{ name: "pf", extension: ".conf", color: "#6d8086" },
	{ name: "pgsql", extension: ".sql", color: "#336791" },
	{ name: "php", extension: ".php", color: "#4f5d95" },
	{ name: "php-template", extension: ".php", color: "#4f5d95" },
	{ name: "plaintext", extension: ".txt", color: "#6d8086" },
	{ name: "pony", extension: ".pony", color: "#6d8086" },
	{ name: "powershell", extension: ".ps1", color: "#012456" },
	{ name: "processing", extension: ".pde", color: "#0096d8" },
	{ name: "profile", extension: ".profile", color: "#6d8086" },
	{ name: "prolog", extension: ".pl", color: "#74283c" },
	{ name: "properties", extension: ".properties", color: "#6d8086" },
	{ name: "protobuf", extension: ".proto", color: "#4885ed" },
	{ name: "puppet", extension: ".pp", color: "#302b6d" },
	{ name: "purebasic", extension: ".pb", color: "#5a6986" },
	{ name: "python", extension: ".py", color: "#3572a5" },
	{ name: "python-repl", extension: ".py", color: "#3572a5" },
	{ name: "q", extension: ".q", color: "#0040cd" },
	{ name: "qml", extension: ".qml", color: "#44a51c" },
	{ name: "r", extension: ".r", color: "#198ce7" },
	{ name: "reasonml", extension: ".re", color: "#ff5847" },
	{ name: "rib", extension: ".rib", color: "#6d8086" },
	{ name: "roboconf", extension: ".cfg", color: "#6d8086" },
	{ name: "routeros", extension: ".rsc", color: "#6d8086" },
	{ name: "rsl", extension: ".rsl", color: "#6d8086" },
	{ name: "ruleslanguage", extension: ".rl", color: "#6d8086" },
	{ name: "rust", extension: ".rs", color: "#dea584" },
	{ name: "sas", extension: ".sas", color: "#b34936" },
	{ name: "scala", extension: ".scala", color: "#c22d40" },
	{ name: "scheme", extension: ".scm", color: "#1e4aec" },
	{ name: "scilab", extension: ".sci", color: "#6d8086" },
	{ name: "scss", extension: ".scss", color: "#c6538c" },
	{ name: "shell", extension: ".sh", color: "#89e051" },
	{ name: "smali", extension: ".smali", color: "#6d8086" },
	{ name: "smalltalk", extension: ".st", color: "#596706" },
	{ name: "sml", extension: ".sml", color: "#dc566d" },
	{ name: "sqf", extension: ".sqf", color: "#3f3f3f" },
	{ name: "sql", extension: ".sql", color: "#e38c00" },
	{ name: "stan", extension: ".stan", color: "#b2011d" },
	{ name: "stata", extension: ".do", color: "#1a5276" },
	{ name: "step21", extension: ".stp", color: "#6d8086" },
	{ name: "stylus", extension: ".styl", color: "#ff6347" },
	{ name: "subunit", extension: ".subunit", color: "#6d8086" },
	{ name: "swift", extension: ".swift", color: "#f05138" },
	{ name: "taggerscript", extension: ".script", color: "#6d8086" },
	{ name: "yaml", extension: ".yaml", color: "#cb171e" },
	{ name: "tap", extension: ".tap", color: "#6d8086" },
	{ name: "tcl", extension: ".tcl", color: "#e4cc98" },
	{ name: "thrift", extension: ".thrift", color: "#d12127" },
	{ name: "tp", extension: ".tp", color: "#6d8086" },
	{ name: "twig", extension: ".twig", color: "#c1d026" },
	{ name: "typescript", extension: ".ts", color: "#3178c6" },
	{ name: "vala", extension: ".vala", color: "#fbe5cd" },
	{ name: "vbnet", extension: ".vb", color: "#945db7" },
	{ name: "vbscript", extension: ".vbs", color: "#15dcdc" },
	{ name: "vbscript-html", extension: ".vbs", color: "#15dcdc" },
	{ name: "verilog", extension: ".v", color: "#b2b7f8" },
	{ name: "vhdl", extension: ".vhd", color: "#adb2cb" },
	{ name: "vim", extension: ".vim", color: "#199f4b" },
	{ name: "wasm", extension: ".wasm", color: "#654ff0" },
	{ name: "wren", extension: ".wren", color: "#383838" },
	{ name: "x86asm", extension: ".asm", color: "#6d8086" },
	{ name: "xl", extension: ".xl", color: "#6d8086" },
	{ name: "xquery", extension: ".xq", color: "#5232e7" },
	{ name: "zephir", extension: ".zep", color: "#118bb1" },
]
